#outer_r = 5.3
outer_r_ = 6.693
inner_r = 3.0
board_size = 0.787

# need to be remeasured if charuco boards are moved
board_A2A=[1.4846,4.972]
board_A2B=[13.272,14.721]
board_A2C=[12.664,9.945]

board_B2A = [14.613,13.236]
board_B2B = [5.01,1.342]
board_B2C = [9.748,12.574]

board_C2A = [13.343,14.631]
board_C2B = [12.512,9.748]
board_C2C = [1.377,5.079]

unit = 'inch'

# will remove
#recorded_center = [562,437] # manually added
#window_A= [[454,801],[667,807]]# manually added
#window_B= [[934,352], [832,169]]# manually added
#window_C= [[308,159], [195,340]]# manually added





